### ISSUE TITLE
Configurable IP Address

### ISSUE THREAD

**Issue by Madic-** [vdcloudcraft/fail2ban-geo-exporter#1] opened 2020-05-25 22:42 UTC
By default the exporter is listening on the ip 0.0.0.0. That's every IP from the host.
Make it configurable so it can be e.g. 127.0.0.1.

Or better, make it IPv6 compatible so it can be [..1] ;)

**Comment by vdcloudcraft** [comment] 2020-05-26 20:27
Good point. It should be just a matter of adding another key in the `conf.yml`, but I'd like to test it and make sure it works as intended. It'll take a day or two until I get around to it.

**Comment by vdcloudcraft** [comment] 2020-05-27 17:51
The configurable IP has been added with 634d8443c76100dcc95d80d0abbe3fa3354bf1ba. IPv6 is currently out of scope I'm afraid, since the exporter only runs on a WSGI `simple_server` and I don't see a simple way to enable it without running a dedicated web server in front of it. I'll reconsider this, should there be an actual demand for it.

**Closed by vdcloudcraft** 2020-05-27 17:51 UTC
